# Generated by Django 3.1.2 on 2020-10-31 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiting', '0004_auto_20201027_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owns',
                                       to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('not_looking_for_job', 'Не ищу работу'),
                                                                 ('considering_offers', 'Рассматриваю предложения'),
                                                                 ('looking_for_job', 'Ищу работу')], max_length=300)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(blank=True,
                                           choices=[('trainee', 'Стажер '), ('junior', 'Джуниор'), ('middle', 'Миддл'),
                                                    ('senior', 'Синьор'), ('lead', 'Лид')], max_length=300)),
                ('education', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('portfolio', models.URLField(blank=True, max_length=150, null=True)),
                ('specialty',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume',
                                   to='recruiting.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
